name: Deploy to GitHub Pages (gh-pages branch)

on:
  push:
    branches:
      - main  # 监听 main 分支的推送

permissions:
  contents: write  # 写入仓库权限

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Create index.html
      run: |
        echo '<!DOCTYPE html>
        <html lang="zh">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>AI 合同销售页</title>
        </head>
        <body style="text-align: center; padding-top: 50px;">
          <h1>$9.99 AI 合同销售页 (占位符)</h1>
          <p>内容已通过 GitHub Actions 成功部署！</p>
        </body>
        </html>' > index.html

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: .
        force_orphan: true
        commit_message: 'Deploy placeholder index.html to gh-pages branch'
